### ISSUE TITLE
New version is not good as previous one.

### ISSUE THREAD

**Issue by Coooi** [subtitle-master/subtitlemaster#7]
This version: http://static.freedownloadmanager.org/s_mac/172/172122_1.jpg
It was the best version ever of this app.
Why did you do such a drastic change to this app?

**Comment by wilkerlucio** [comment]
Hi @Coooi,

Thanks for using Subtitle Master.

Yes, some other people also told me they liked the first version better, and I can understand that because the first was built using native API's, so it feels much better as a native app than the current implementation that uses a browser for rendering the UI.

There are two main reasons it did change, and here they are:

1. On the first version I was using Objective-C as the language, and I'm not very good at it, the codebase was a mess, so updates were very slow, costly and complicated, so was a very frustrating place to work so that I wouldn't progress on it. Now instead I can use the technologies that I know better, that enabled a clean code base, smooth updates, and more interest from me to keep working on it (although it was frozen for a while, being busy with other projects, but the community is welcome to make progress on it, I would be happy to help if anyone wants to take the task).

2. This new version is multi-platform, before you could only run it on MacOS systems, now you can run on Windows too, those new users (and Windows has a gigantic share of people that like this kind of program) will be using Subtitle Master, and so by it sharing their subtitles, which in turn improves the databases making it better for everybody, so we get more subtitles :).

I hope you can understand and enjoy Subtitle Master, at some day I would like to give a try to [React Native for MacOSX](https://github.com/ptmt/react-native-macos), so I could use the technologies that I love and still provide a native interface, but it's really in the limbo, I can't give you any possible dates about when this is going to happen (or if it's going to happen at all).
